[project]
org-name = "ballerinax"
version = "2.0.0"
license= ["Apache-2.0"]
authors = ["Ballerina"]
keywords = ["azure", "time-series", "insights", "TSI"]
repository = "https://github.com/ballerina-platform/module-ballerinax-azure.timeseries"
