[project]
org-name = "ballerinax"
version = "1.0.0"
license= ["Apache-2.0"]
authors = ["WSO2"]
keywords = ["azure", "time-series", "insights"]
repository = "https://github.com/ballerina-platform/module-azuretimeseries"
