name: CI

on: [push, pull_request]

jobs:
    build:

        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v2
            - name: Ballerina Build
              uses: ballerina-platform/ballerina-action/@swan-lake-connector-release
              with:
                  args:
                      build -a -c
              env:
                  ENV_FQDN: ${{ secrets.ENV_FQDN }}
                  TENANT_ID: ${{ secrets.TENANT_ID }}
                  CLIENT_ID: ${{ secrets.CLIENT_ID }}
                  CLIENT_SECRET: ${{ secrets.CLIENT_SECRET }}
